### ISSUE TITLE
Dependencies for building are not listed.

### ISSUE THREAD

**Issue by JamesChristie** [lhw/gogdownloader#1]
Still trying to get it to build after I track down where some of these .h files come from. An explicit list of dependencies somewhere would be amazing though. =)

**Comment by lhw** [comment]
Currently there is not much of a downloader yet. You would have to hardcode the ids into the main function to start a download. Im working on a decent model with either a select() oder a libevent2 based approach. Im testing both right now. As soon as the downloading part is done I will add a decent build system so these issues won't be there for long.

If you till want to compile the code:
liboauth is the one from sourceforge. http://liboauth.sourceforge.net/ and libjson is json-c from http://oss.metaparadigm.com/json-c/ Both are available on debian/ubuntu as liboauth-dev and libjson0-dev. I personally had a problem using the liboauth provided by ubuntu which is linked against libnss. All requests made through the lib would stall. Using the same package linked against libssl worked just fine. I will have to analyze that further and create a patch or bugreport.
